### ISSUE TITLE
Can't generate Parcelable for fields in child classes

### ISSUE THREAD

**Issue by aaronhe42** [mcharmas/android-parcelable-intellij-plugin#35]
After upgraded to latest version 0.6.3, it seems I can no longer generate `Parcelable` in child classes regardless of what accessors those fields have.

For example:

	public class Person {
	    String name;
	}

	public class Employee extends Person {
	    String company;
	}

The `Employee` class can only generate `Parcelable` for its own fields, `company` but not `name`. It might make sense. But what if the parent class doesn't implement `Parcelable` at all and I only want child classes to implement `Parcelable`?

Is this a design change?

**Comment by mcharmas** [comment]
Yep, this is a bug indeed. I've recently added support for inheritance but of ```Parcelable``` type. I've ommited regular Parcelation because I rarely do that. With parcelation I follow the same rule as with serialization. For the child class to be parcelable the parent should be responsible for parcelation of itself.

It should be fixed in new release.

**Comment by aaronmix** [comment]
Yea I agree with you. But the problem I have is the parent classes are from somewhere I don't have control of. I think it would be nice if plugin could check wether the parent class actually implements `Parcelable`, if so, fields from parent class should be prevented from generated in child class, otherwise just let the child to parcel those fields.

**Comment by DariusL** [comment]
I think a class should only parcel itself and call writeToParcel on the parent (which would correctly fail in this case). My idea would be to create an abstract ParcelablePerson.
